// 자동 생성됨 -- build_data.py가 생성. 직접 편집하지 마세요.
// Source: 부산_맛집_리서치_v1776765610.xlsx
// 엑셀 수정 후 `python build_data.py`로 재생성.

const MEAL = [
  {
    "region": "광안리",
    "name": "자매국밥",
    "rating": 5.0,
    "src": "식신(한줄평)",
    "kakao": 2.8,
    "addr": "부산 수영구 민락본동로27번길 56",
    "menu": "돼지국밥, 순대국밥, 섞어국밥, 수육백반",
    "wait": "주말 대기 / 평일 바로 입장",
    "praise": "맑고 칼칼·롯데 선수 단골·주택개조",
    "complaint": "-",
    "hours": "월~토 10:00-21:00, 일 휴무",
    "memo": "수영구 민락본동로27번길 56",
    "url": "https://map.naver.com/p/search/%EC%9E%90%EB%A7%A4%EA%B5%AD%EB%B0%A5%20%EB%AF%BC%EB%9D%BD",
    "photo": "맛집_사진/01_자매국밥.jpg"
  },
  {
    "region": "민락",
    "name": "수변최고돼지국밥 민락본점",
    "rating": 4.8,
    "src": "다이닝코드(맛)",
    "kakao": 4.1,
    "addr": "부산 수영구 광안해변로370번길 9-32 1층",
    "menu": "항정국밥 13,000 / 고기국밥 10,000 / 항정수백 15,000",
    "wait": "2-3시간 / 테이블링 원격 20분",
    "praise": "깔끔 인테리어·친절·항정 전용",
    "complaint": "웨이팅 매우 심함",
    "hours": "24시간 연중무휴",
    "memo": "본점 기준 (광안해변로370번길 9-32)",
    "url": "https://map.naver.com/p/search/%EC%88%98%EB%B3%80%EC%B5%9C%EA%B3%A0%EB%8F%BC%EC%A7%80%EA%B5%AD%EB%B0%A5%20%EB%AF%BC%EB%9D%BD%EB%B3%B8%EC%A0%90",
    "photo": "맛집_사진/02_수변최고돼지국밥_민락본점.jpg"
  },
  {
    "region": "전포",
    "name": "치킨버거클럽 전포",
    "rating": 4.7,
    "src": "다이닝코드",
    "kakao": 4.4,
    "addr": "부산 부산진구 서전로58번길 121 1층",
    "menu": "B.L.T, 내쉬빌핫치킨2조각",
    "wait": "인기로 대기 있음",
    "praise": "맛4.8·힙한 인테리어·버거 노1",
    "complaint": "-",
    "hours": "매일 11:40-21:00 (평일 휴게 16:00-17:00)",
    "memo": "광안점과 메뉴 상이",
    "url": "https://map.naver.com/p/search/%EC%B9%98%ED%82%A8%EB%B2%84%EA%B1%B0%ED%81%B4%EB%9F%BD%20%EC%A0%84%ED%8F%AC",
    "photo": "맛집_사진/03_치킨버거클럽_전포.jpg"
  },
  {
    "region": "남포",
    "name": "미친막창",
    "rating": 4.7,
    "src": "다이닝코드(Tripadvisor 5.0)",
    "kakao": 4.3,
    "addr": "부산 중구 광복로 16-2 1층 (부평동1가 38-1)",
    "menu": "양념/소금막창, 파채라면(무료), 팥빙수(무료)",
    "wait": "-",
    "praise": "구워서 서빙·팥빙수 무료·13가지 된장소스",
    "complaint": "-",
    "hours": "매일 14:30-24:00 (화는 늦은 오픈 가능)",
    "memo": "중구 흑교로35번길 5",
    "url": "https://map.naver.com/p/search/%EB%AF%B8%EC%B9%9C%EB%A7%89%EC%B0%BD%20%EB%82%A8%ED%8F%AC",
    "photo": "맛집_사진/04_미친막창.jpg"
  },
  {
    "region": "부암",
    "name": "이탈리아피자 부암",
    "rating": 4.6,
    "src": "다이닝코드(맛5.0)",
    "kakao": 4.4,
    "addr": "부산 부산진구 백양순환로 110 1층 (부암동 477-2)",
    "menu": "치즈크러스트피자, 도이치페스타, 고르곤졸라",
    "wait": "-",
    "praise": "맛 최상·연중무휴·치즈",
    "complaint": "가격 다소 높음(가격 3.0)",
    "hours": "매일 11:30-01:00 (연중무휴)",
    "memo": "백양순환로 110",
    "url": "https://map.naver.com/p/search/%EC%9D%B4%ED%83%88%EB%A6%AC%EC%95%84%ED%94%BC%EC%9E%90%20%EB%B6%80%EC%95%94",
    "photo": "맛집_사진/05_이탈리아피자_부암.jpg"
  },
  {
    "region": "전포(본점참조)",
    "name": "이재모피자 본점",
    "rating": 4.5,
    "src": "다이닝코드",
    "kakao": 4.3,
    "addr": "부산 중구 광복중앙로 31 중앙아파트 상가 2층",
    "menu": "피자, 김치볶음밥(본점 전용), 갈릭소스",
    "wait": "일평균 988명 (캐치테이블 부산 1위)",
    "praise": "치즈 넉넉·가성비·김볶+갈릭소스 필수",
    "complaint": "웨이팅 극심, 김볶은 본점에서만",
    "hours": "월~토 10:00-21:10 (LO 20:30), 일 휴무",
    "memo": "김볶+신상소스는 본점(광복동) 전용. 유저 '전포권' 분류지만 본점 데이터.",
    "url": "https://map.naver.com/p/search/%EC%9D%B4%EC%9E%AC%EB%AA%A8%ED%94%BC%EC%9E%90%20%EA%B4%91%EB%B3%B5%EB%8F%99%20%EB%B3%B8%EC%A0%90",
    "photo": "맛집_사진/06_이재모피자_본점.jpg"
  },
  {
    "region": "광안리",
    "name": "초필살돼지구이 광안직영점",
    "rating": 4.5,
    "src": "다이닝코드(맛4.9)",
    "kakao": null,
    "addr": "부산 수영구 광남로108번길 9 1층",
    "menu": "돼지껍데기, 삼겹살",
    "wait": "기본 3시간 / 캐치테이블 필수",
    "praise": "직원 직접 굽기·겉바속촉 껍데기·단짠",
    "complaint": "극심한 웨이팅",
    "hours": "매일 12:00-01:00 (휴게 15:00-17:00)",
    "memo": "금련산역 도보권",
    "url": "https://map.naver.com/p/search/%EC%B4%88%ED%95%84%EC%82%B4%EB%8F%BC%EC%A7%80%EA%B5%AC%EC%9D%B4%20%EA%B4%91%EC%95%88%EC%A7%81%EC%98%81%EC%A0%90",
    "photo": "맛집_사진/07_초필살돼지구이_광안직영점.jpg"
  },
  {
    "region": "광안리",
    "name": "톤쇼우 광안점",
    "rating": 4.5,
    "src": "다이닝코드",
    "kakao": null,
    "addr": "부산 수영구 광안해변로279번길 13 1층",
    "menu": "버크셔K특로스카츠 17,500 / 모듬카츠",
    "wait": "일평균 798명(부산 2위) / 2시간",
    "praise": "육즙·겉바속촉·카레 필수",
    "complaint": "웨이팅 심함, 테이블링 필수",
    "hours": "매일 11:00-21:30 (LO 20:30)",
    "memo": "택시기사 왈 줄 더 김",
    "url": "https://map.naver.com/p/search/%ED%86%A4%EC%87%BC%EC%9A%B0%20%EA%B4%91%EC%95%88%EC%A0%90",
    "photo": "맛집_사진/08_톤쇼우.jpg"
  },
  {
    "region": "해운대",
    "name": "나가하마만게츠 해리단길",
    "rating": 4.5,
    "src": "다이닝코드·미쉐린 2024",
    "kakao": 4.2,
    "addr": "부산 해운대구 우동1로 57 대영빌딩 1층",
    "menu": "돈코츠라멘 10,000 / 교자 7,000 / 세트 16,000",
    "wait": "일평균 389명(부산 6위) / 오픈전부터",
    "praise": "정통 돈코츠·교자·36시간 육수",
    "complaint": "브레이크타임 주의",
    "hours": "매일 11:00-20:30",
    "memo": "후쿠오카 본점 한국 1호",
    "url": "https://map.naver.com/p/search/%EB%82%98%EA%B0%80%ED%95%98%EB%A7%88%EB%A7%8C%EA%B2%8C%EC%B8%A0%20%ED%95%B4%EB%A6%AC%EB%8B%A8%EA%B8%B8",
    "photo": "맛집_사진/09_나가하마만게츠.jpg"
  },
  {
    "region": "광안리",
    "name": "융캉찌에",
    "rating": 4.4,
    "src": "다이닝코드·미쉐린가이드 2025",
    "kakao": null,
    "addr": "부산 수영구 광안해변로277번길 10 1층",
    "menu": "우육탕면 10,500 / 탄탄면 9,500 / 레몬치킨 8,000",
    "wait": "상시 줄 / 실시간 대기 확인 필수",
    "praise": "대만 현지맛·진한 국물·야시장 분위기",
    "complaint": "자리 적음",
    "hours": "매일 11:00-21:30 (휴게 15:00-16:00, LO 21:00)",
    "memo": "광안해변 도보 3분, 미쉐린 부산 2025",
    "url": "https://map.naver.com/p/search/%EC%9C%B5%EC%BA%89%EC%B0%8C%EC%97%90%20%EA%B4%91%EC%95%88%EB%A6%AC",
    "photo": "맛집_사진/10_융캉찌에.jpg"
  },
  {
    "region": "광안리",
    "name": "바로해장",
    "rating": 4.3,
    "src": "다이닝코드",
    "kakao": null,
    "addr": "부산 수영구 광남로94번길 2 1층 101호",
    "menu": "소한마리해장국, 갈빗살수육, 수육냉면무침",
    "wait": "점심·주말 대기",
    "praise": "맑은 국물·냄새 없음·진한 육향",
    "complaint": "주차장 없음",
    "hours": "매일 09:00-22:00 (휴게 15:30-17:00)",
    "memo": "광안 공영주차장 이용",
    "url": "https://map.naver.com/p/search/%EB%B0%94%EB%A1%9C%ED%95%B4%EC%9E%A5%20%EA%B4%91%EC%95%88",
    "photo": "맛집_사진/11_바로해장.jpg"
  },
  {
    "region": "서면",
    "name": "라라관 서면본점",
    "rating": 4.2,
    "src": "뽈레",
    "kakao": 3.9,
    "addr": "부산 부산진구 동천로 47-1 1층",
    "menu": "마라전골 32,400 / 소고기마라훠궈전골 29,500 / 꿔바로우",
    "wait": "저녁 대기 있음",
    "praise": "중독성·양 많음·국내 최초 훠궈전골",
    "complaint": "평일 브레이크타임 15-17시",
    "hours": "매일 12:00-23:00 (휴게 15:00-17:00, LO 22:00)",
    "memo": "전포역 5번출구 329m",
    "url": "https://map.naver.com/p/search/%EB%9D%BC%EB%9D%BC%EA%B4%80%20%EC%84%9C%EB%A9%B4%EB%B3%B8%EC%A0%90",
    "photo": "맛집_사진/12_라라관.jpg"
  },
  {
    "region": "초량/부산역",
    "name": "신발원",
    "rating": 4.2,
    "src": "다이닝코드",
    "kakao": 3.8,
    "addr": "부산 동구 대영로243번길 62 1층",
    "menu": "군만두, 고기만두, 새우만두, 찐만두, 콩국",
    "wait": "식사시간 1시간+",
    "praise": "3대째 70년 노포·친절·촉촉 육즙",
    "complaint": "주차장 없음",
    "hours": "수~월 10:00-21:00, 화 휴무",
    "memo": "차이나타운, 혼밥석·키오스크 편리",
    "url": "https://map.naver.com/p/search/%EC%8B%A0%EB%B0%9C%EC%9B%90%20%EC%B0%A8%EC%9D%B4%EB%82%98%ED%83%80%EC%9A%B4",
    "photo": "맛집_사진/13_신발원.jpg"
  },
  {
    "region": "전포/서면",
    "name": "피자드시우",
    "rating": 4.0,
    "src": "다이닝코드(81/100)",
    "kakao": null,
    "addr": "부산 부산진구 중앙대로692번길 46-7 1층",
    "menu": "크림불고기파스타, 치즈크러스트피자",
    "wait": "주말 1시간+",
    "praise": "임실치즈·수제도우·치즈 늘어남",
    "complaint": "조리 15~20분 소요",
    "hours": "매일 13:00-24:00 (LO 23:00)",
    "memo": "서면 엔젤호텔 1층",
    "url": "https://map.naver.com/p/search/%ED%94%BC%EC%9E%90%EB%93%9C%EC%8B%9C%EC%9A%B0%20%EC%84%9C%EB%A9%B4",
    "photo": "맛집_사진/14_피자드시우.jpg"
  },
  {
    "region": "중앙동",
    "name": "상짱",
    "rating": 3.9,
    "src": "망고플레이트(다이닝 맛4.9)",
    "kakao": 3.6,
    "addr": "부산 중구 해관로 59-1 1층",
    "menu": "텐푸라정식 세트 14,800 / 우동",
    "wait": "-",
    "praise": "갓튀긴 튀김·정통 일식·생활의달인",
    "complaint": "-",
    "hours": "월~토 11:30-20:30 (휴게 14:30-17:00), 일 휴무",
    "memo": "",
    "url": "https://map.naver.com/p/search/%EC%83%81%EC%A7%B1%20%EC%A4%91%EC%95%99%EB%8F%99",
    "photo": "맛집_사진/15_상짱.jpg"
  },
  {
    "region": "남천",
    "name": "왕초장",
    "rating": 3.7,
    "src": "식신",
    "kakao": 4.3,
    "addr": "부산 수영구 광안해변로15번길 77 지하1층 95호",
    "menu": "상차림, 해물파전",
    "wait": "-",
    "praise": "남천해변시장 최고 초장집",
    "complaint": "-",
    "hours": "매일 12:00-22:30",
    "memo": "",
    "url": "https://map.naver.com/p/search/%EC%99%95%EC%B4%88%EC%9E%A5%20%EB%82%A8%EC%B2%9C",
    "photo": "맛집_사진/16_왕초장.jpg"
  },
  {
    "region": "전포",
    "name": "프리윌피자",
    "rating": null,
    "src": "다이닝코드(SET 3.6/4.0)",
    "kakao": 4.6,
    "addr": "부산 부산진구 전포대로224번길 26 1층",
    "menu": "에그포테이토, 프리윌피자, 양송이튀김",
    "wait": "토요일 ~2시간",
    "praise": "에그포테이토·직원 친절·사이드 다양",
    "complaint": "-",
    "hours": "매일 11:00-21:30",
    "memo": "",
    "url": "https://map.naver.com/p/search/%ED%94%84%EB%A6%AC%EC%9C%8C%ED%94%BC%EC%9E%90%20%EC%A0%84%ED%8F%AC",
    "photo": "맛집_사진/17_프리윌피자.jpg"
  },
  {
    "region": "광안리/남천",
    "name": "안목(安木)",
    "rating": null,
    "src": "미쉐린 빕구르망 2024-25",
    "kakao": 4.0,
    "addr": "부산 수영구 광남로22번길 3 남천센텀스카이뷰 1층 101호",
    "menu": "돼지국밥, 머릿고기국밥",
    "wait": "일평균 334명(부산 9위) / 점심 58팀",
    "praise": "미쉐린 빕구르망·정갈·깔끔한 돼지국밥",
    "complaint": "예약 사실상 필수",
    "hours": "매일 11:00-21:00 (LO 20:30)",
    "memo": "남천역 1번출구 도보 5분, 캐치테이블 필수",
    "url": "https://map.naver.com/p/search/%EC%95%88%EB%AA%A9%20%EB%82%A8%EC%B2%9C%20%EB%8F%BC%EC%A7%80%EA%B5%AD%EB%B0%A5",
    "photo": "맛집_사진/18_안목.jpg"
  },
  {
    "region": "민락",
    "name": "미락슈퍼",
    "rating": null,
    "src": "미쉐린가이드",
    "kakao": 3.6,
    "addr": "부산 수영구 민락본동로31번길 46 1층",
    "menu": "제철요리 오마카세 코스, 숯불 고기 한상차림, 와인",
    "wait": "예약제 (좌석 6개)",
    "praise": "미쉐린·제철재료·와인 페어링",
    "complaint": "예약 어려움, 좌석 적음",
    "hours": "화·수 휴무 (영업시간 카카오 미표시)",
    "memo": "⚠️ 유저가 '포차' 분류했으나 실제는 미쉐린 오마카세/와인바. 확인 필요.",
    "url": "https://map.naver.com/p/search/%EB%AF%B8%EB%9D%BD%EC%8A%88%ED%8D%BC%20%EB%AF%BC%EB%9D%BD",
    "photo": "맛집_사진/19_미락슈퍼.jpg"
  },
  {
    "region": "초량",
    "name": "스완양분식",
    "rating": null,
    "src": "다이닝코드(부분 59~64점)",
    "kakao": 3.6,
    "addr": "부산 동구 중앙대로236번길 7-5 1층",
    "menu": "수제돈까스, 비후까스, 함박스테이크, 오무라이스, 옛날우동",
    "wait": "점심 만석",
    "praise": "옛날돈까스·바삭·인플루언서 성지",
    "complaint": "취향 분분",
    "hours": "월~토 11:30-20:00, 일 휴무",
    "memo": "영화 <아저씨> 촬영지, 범일→초량 이전",
    "url": "https://map.naver.com/p/search/%EC%8A%A4%EC%99%84%EC%96%91%EB%B6%84%EC%8B%9D%20%EC%B4%88%EB%9F%89",
    "photo": "맛집_사진/20_스완양분식.jpg"
  }
];

const BAKERY = [
  {
    "region": "망미",
    "name": "디저트시네마",
    "rating": 5.0,
    "src": "트립어드바이저",
    "kakao": 3.9,
    "addr": "부산 연제구 쌍미천로 32-1 1층",
    "menu": "시네마페스츄리, 크루아상, 파이",
    "wait": "현장등록만 / 오픈 10시부터 대기(12시 오픈)",
    "praise": "페스츄리 블루리본 5개·인생크루아상·인테리어",
    "complaint": "운영시간 짧음(토·일만 + 일부 수요일)",
    "hours": "토·일 12:00-16:00 + 둘째/마지막주 수요일",
    "memo": "연제구 쌍미천로 32-1",
    "url": "https://map.naver.com/p/search/%EB%94%94%EC%A0%80%ED%8A%B8%EC%8B%9C%EB%84%A4%EB%A7%88%20%EB%A7%9D%EB%AF%B8",
    "photo": "맛집_사진/21_디저트시네마.jpg"
  },
  {
    "region": "초량",
    "name": "초량온당",
    "rating": 4.8,
    "src": "테이블링",
    "kakao": 4.3,
    "addr": "부산 동구 초량중로 135 1층",
    "menu": "맘모스 6,700~7,700 / 크럼블 5,700~6,500 / 크림빵·스콘·에그타르트",
    "wait": "30분전 대기 / 맘모스 대기 30번 내외 소진",
    "praise": "맘모스·분위기·친절(4.8)",
    "complaint": "월·일 휴무, 품절 빠름",
    "hours": "화~토 12:00-19:00, 월·일 휴무",
    "memo": "동구 초량중로 135",
    "url": "https://map.naver.com/p/search/%EC%B4%88%EB%9F%89%EC%98%A8%EB%8B%B9",
    "photo": "맛집_사진/22_초량온당.jpg"
  },
  {
    "region": "전포",
    "name": "희와제과",
    "rating": 4.6,
    "src": "다이닝코드(망플 4.0)",
    "kakao": 3.7,
    "addr": "부산 부산진구 전포대로246번길 6 1층",
    "menu": "앙소보루, 맘모스, 밤팥빵 5,200, 밤호박파운드 5,200",
    "wait": "오픈런 / 인기빵 빠른 소진",
    "praise": "앙소보루·맘모스·담백한 빵+팥",
    "complaint": "오픈 직후 소진 많음",
    "hours": "목~월 11:00-19:00, 화·수 휴무",
    "memo": "",
    "url": "https://map.naver.com/p/search/%ED%9D%AC%EC%99%80%EC%A0%9C%EA%B3%BC%20%EC%A0%84%ED%8F%AC",
    "photo": "맛집_사진/23_희와제과.jpg"
  },
  {
    "region": "광안리",
    "name": "더베이베이커리",
    "rating": 4.6,
    "src": "다이닝코드(맛5.0 친절5.0)",
    "kakao": 3.9,
    "addr": "부산 수영구 수영로510번길 30 1층",
    "menu": "카야소금빵, 맘모스",
    "wait": "오픈 1시간 / 캐치테이블 10:30 현장·11:00 온라인",
    "praise": "인생빵·카야소금빵·친절",
    "complaint": "매장 협소(2팀), 가격 다소 높음(3.0)",
    "hours": "목~월 11:30-17:00, 화·수 휴무",
    "memo": "금련산역 도보 6분, 수영로510번길 30",
    "url": "https://map.naver.com/p/search/%EB%8D%94%EB%B2%A0%EC%9D%B4%EB%B2%A0%EC%9D%B4%EC%BB%A4%EB%A6%AC%20%EA%B4%91%EC%95%88",
    "photo": "맛집_사진/24_더베이베이커리.jpg"
  },
  {
    "region": "광안리",
    "name": "서희와제과",
    "rating": 4.5,
    "src": "다이닝코드(커피)",
    "kakao": 4.0,
    "addr": "부산 수영구 광남로 89 1층 (광안동 184-8)",
    "menu": "팥크림치즈, 호박치즈, 호옥이, 흑쑥이, 밤팥빵, 소보루, 휘낭시에",
    "wait": "있음 / 빵 계속 구워져 나옴",
    "praise": "재료 본연의 맛·담백·빵 종류 많음",
    "complaint": "내부 협소, 취식공간 없음(테이크아웃)",
    "hours": "수~일 (영업시간 카카오 미표시), 월·화 휴무",
    "memo": "전포 '희와제과' 자매 매장. 전포 희와제과와 다른 매장.",
    "url": "https://map.naver.com/p/search/%EC%84%9C%ED%9D%AC%EC%99%80%EC%A0%9C%EA%B3%BC%20%EA%B4%91%EC%95%88",
    "photo": "맛집_사진/25_서희와제과.jpg"
  },
  {
    "region": "초량",
    "name": "베이크백(Bake Back)",
    "rating": 3.4,
    "src": "뽈레 (네이버 스마트스토어 4.96)",
    "kakao": 4.2,
    "addr": "부산 동구 초량중로 53 1-2층",
    "menu": "모찌빵 10종, 브라우니 5종, 종합선물세트",
    "wait": "-",
    "praise": "국내 최초 모찌빵·쫀득 피·종류 다양",
    "complaint": "-",
    "hours": "월·화·목~일 10:00-18:00, 수 휴무",
    "memo": "동구 초량중로 53",
    "url": "https://map.naver.com/p/search/%EB%B2%A0%EC%9D%B4%ED%81%AC%EB%B0%B1%20%EC%B4%88%EB%9F%89",
    "photo": "맛집_사진/26_베이크백.jpg"
  },
  {
    "region": "전포",
    "name": "크리미(CREAMY)",
    "rating": null,
    "src": "식신/다이닝코드",
    "kakao": 4.3,
    "addr": "부산 부산진구 서전로46번길 14 1층",
    "menu": "쿠키슈, 모찌뿌요, 크림푸딩, 깨찰슈, 프로테피롤, 수건케이크",
    "wait": "점심 놓치면 대기",
    "praise": "동물성크림 전용·독특한 디저트·이국적",
    "complaint": "예약 불가 (현장만)",
    "hours": "수~일 (영업시간 카카오 미표시), 월·화 휴무",
    "memo": "카톡채널 '크리미' 문의",
    "url": "https://map.naver.com/p/search/%ED%81%AC%EB%A6%AC%EB%AF%B8%20%EC%A0%84%ED%8F%AC",
    "photo": "맛집_사진/27_크리미.jpg"
  },
  {
    "region": "명륜",
    "name": "쿠루미 과자점",
    "rating": null,
    "src": "식신/인스타 리뷰",
    "kakao": null,
    "addr": "부산 동래구 온천천로 71-1 1층",
    "menu": "숙성스콘, 모찌, 메론빵, 다크초코소라빵, 야끼소바빵, 팥빵, 시오 포카치오, 빙수, 푸딩",
    "wait": "동네주민 오픈런",
    "praise": "일본풍 감성·푸딩 종류 많음·깔끔",
    "complaint": "-",
    "hours": "수~월 (영업시간 카카오 미표시), 화 휴무",
    "memo": "명륜역 앞 (동래구)",
    "url": "https://map.naver.com/p/search/%EC%BF%A0%EB%A3%A8%EB%AF%B8%20%EA%B3%BC%EC%9E%90%EC%A0%90%20%EB%AA%85%EB%A5%9C",
    "photo": "맛집_사진/28_쿠루미과자점.jpg"
  }
];
